server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yikitchen
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yanghao
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  type-aliases-package: com.qfedu.yikitchen.pojo
  mapper-locations: classpath:mapper/*.xml
